# Generated by Django 2.1.3 on 2018-11-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
