# Generated by Django 2.1.3 on 2018-11-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0008_auto_20181108_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='descripcionMascota',
            new_name='generomascota',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='codigoMascota',
            new_name='idMascota',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='nombreMascota',
            new_name='mascotaname',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='razaMascota',
            new_name='raza',
        ),
    ]
