# Generated by Django 2.1.3 on 2018-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0009_auto_20181108_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(default='Adoptantes', max_length=20),
        ),
    ]
