# Generated by Django 2.1.3 on 2018-11-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0012_auto_20181109_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
    ]
