# Generated by Django 2.1.3 on 2018-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0013_remove_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default=0, upload_to='fotosMascota/'),
            preserve_default=False,
        ),
    ]
